import "./globals.css";
import { Inter, Roboto } from 'next/font/google'
import Header from '@/app/components/header';
import Footer from "./components/footer";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} font-sans antialiased`}
      >

      <Header />,
        {children}
        <Footer/>
      </body>
    </html>
  );
}
